replicaCount: 1

image:
  repository: bijukunjummen/sample-backend-app
  tag: 0.0.3-SNAPSHOT
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

app:
  containerPort: 8080
  healthCheckPath: /
  environment: {}
  secrets: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  tls: []

resources:
  constraints: 
    enabled: false
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi